[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv ; Expanding app partition for TFLite Micro 96KB arena
lib_deps = 
	electroniccats/MPU6050@^1.0.0
	olikraus/U8g2@^2.34.15
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
